version: 0.0
os: linux
files:
  - source: /
    destination: /
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: install_nginx.sh
      timeout: 180
      runas: root

ApplicationStart:
    - location: start_nginx.sh 
      timeout: 300 
      runas: root
  